# Site settings
title: "@xerocuil"
description: A collection of development notes centered mostly around Linux/Python.
url: "http://xerocuil.github.io"
username:  xerocuil
github_url:  https://github.com/xerocuil
twitter_url:  https://twitter.com/xerocuil

# Build settings
markdown: kramdown

collections:
  projects:
    output: true
  gists:
    output: true

defaults:
  - scope:
      path: ""
      type: "gists"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

exclude: [gems]

sass:
  style: compressed